default: &default
  adapter: postgresql
  encoding: utf8
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  username: <%= ENV.fetch('DATABASE_USER', (`whoami`).strip) %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>

development:
  <<: *default
  database: pandora_development

test:
  <<: *default
  database: pandora_test

staging:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'pandora_staging') %>

production:
  <<: *default
  database: pandora_production
